services:
  - type: web
    name: coto2-ba-api
    runtime: python
    buildCommand: pip install uv && uv sync --frozen && uv cache prune --ci
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /
